set(CREATIVE_SUITE_APP_VERSIONS_FILE "${PROJECT_SOURCE_DIR}/packaging/app-versions.json")
file(READ "${CREATIVE_SUITE_APP_VERSIONS_FILE}" CREATIVE_SUITE_APP_VERSIONS_JSON)
foreach(_app_id IN ITEMS hub video-editor image-editor motion-editor)
    string(JSON _app_version ERROR_VARIABLE _version_error
        GET "${CREATIVE_SUITE_APP_VERSIONS_JSON}" applications "${_app_id}" version)
    if(_version_error)
        message(FATAL_ERROR "Missing version for '${_app_id}' in packaging/app-versions.json: ${_version_error}")
    endif()
    if(NOT _app_version MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+$")
        message(FATAL_ERROR "Invalid semantic version '${_app_version}' for '${_app_id}'.")
    endif()
    string(REPLACE "-" "_" _app_key "${_app_id}")
    string(TOUPPER "${_app_key}" _app_key)
    set(CREATIVE_SUITE_VERSION_${_app_key} "${_app_version}")
endforeach()
